controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
      - arm_base_link
      - arm_joint_01
      - arm_joint_02
      - arm_joint_03
      #- arm_joint_04
      #- arm_joint_05
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity